name: Build pysam Windows wheel

on:
  workflow_dispatch:

jobs:
  build-wheel:
    runs-on: ubuntu-latest

    steps:
      - name: Clone pysam source manually
        run: |
          git clone https://github.com/pysam-developers/pysam.git
          cd pysam
          git checkout tags/v0.22.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.16.5

      - name: Build Windows wheels
        run: |
          cd pysam
          CIBW_PLATFORM=windows \
          CIBW_ARCHS=AMD64 \
          CIBW_BUILD="cp310-win_amd64" \
          CIBW_SKIP="pp*" \
          CIBW_ENVIRONMENT='HTSLIB_CONFIGURE_OPTIONS=--disable-libcurl' \
          cibuildwheel --output-dir wheelhouse

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: pysam-windows-wheels
          path: pysam/wheelhouse/
